# Generated by Django 3.2.4 on 2021-07-01 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Colaboradores',
            fields=[
                ('Rut', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='rut')),
                ('Image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('NombreCompleto', models.CharField(max_length=40, verbose_name='Nombre completo')),
                ('Telefono', models.CharField(max_length=9, verbose_name='Numero de telefono')),
                ('Direccion', models.CharField(max_length=30, verbose_name='Direccion')),
                ('Email', models.CharField(max_length=30, verbose_name='Email')),
                ('Contrasenia', models.CharField(max_length=30, verbose_name='Contraseña')),
                ( 'pais',models.CharField(max_length=10,verbose_name='pais')),
            ],
        ),
    ]
